given {
  def foo = 1  // error
}